# Generated by Django 2.0.1 on 2018-01-16 01:16

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
